Rails.application.routes.draw do
  get 'forms/diligenciador'
  get 'forms/visualizador'
  get 'forms/formularios'
  get 'forms/guardar_formulario_staff'
  get 'alertas/asignar_grupo'
  get 'alertas/gestionar_grupo'
  get 'alertas/designar_grupos'
  get 'alertas/terminar_gestion'
  get 'oracle/ordenes_hospitalarias_ambulatorias'
  devise_for :users
  root 'order_staffs#staff'
  get 'order_staffs/todos_los_pacientes'
  get 'order_staffs/pendientes'
  get 'order_staffs/completados'
  get 'order_staffs/todos_los_pacientes'
  get 'order_staffs/envio_excel'
  get 'order_staffs/sin_grupo'
  get 'order_staffs/charts'
  get 'order_staffs/gestionados'
  get 'order_staffs/asignar'
  get 'order_staffs/gestionador'
  get 'order_staffs/ver_gestion'
  get 'order_staffs/staff'
  get 'order_staffs/cambiar_estado_tumor'
  get 'order_staffs/cirugia_mohs'
  get 'order_staffs/dermatologia'
  get 'order_staffs/linfomas_cutaneos'
  get 'order_staffs/funcional_clinico'
  get 'order_staffs/funcional_quirurgico'
  get 'order_staffs/torax'
  get 'order_staffs/gastrointestinal'
  get 'order_staffs/mastologia'
  get 'order_staffs/terapias_especiales'
  get 'order_staffs/oncologia'
  get 'order_staffs/cirugia_cabeza_cuello'
  get 'order_staffs/tumores_pelvicos'
  get 'order_staffs/peritoneo'
  get 'order_staffs/hematologia'
  get 'order_staffs/enrutador'
  get 'errors/sin_grupo'
  get 'errors/sin_item'
  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unacceptable'
  get '/500', to: 'errors#server_errors'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
